name: run server tests on pull request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up the Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Run Maven tests
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/scripts/test.sh"
          "${GITHUB_WORKSPACE}/.github/scripts/test.sh"
